### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by MaxNamazov** [lcjnil/react-redux-scaffold#1]
I'm getting error right after executing `gulp serve` command. 

```
ERROR in ./src/reducers/todos.js
Module build failed: RangeError: Maximum call stack size exceeded
    at Array.indexOf (native)
    at stripsPosition (/Users/Max/projects/wfb/i18n-sync-tool/node_modules/eslint/lib/rules/no-duplicate-case.js:24:52)
    at stripsPosition (/Users/Max/projects/wfb/i18n-sync-tool/node_modules/eslint/lib/rules/no-duplicate-case.js:27:36)
    at stripsPosition (/Users/Max/projects/wfb/i18n-sync-tool/node_modules/eslint/lib/rules/no-duplicate-case.js:27:36)
    at stripsPosition (/Users/Max/projects/wfb/i18n-sync-tool/node_modules/eslint/lib/rules/no-duplicate-case.js:27:36)
    at stripsPosition (/Users/Max/projects/wfb/i18n-sync-tool/node_modules/eslint/lib/rules/no-duplicate-case.js:27:36)
    at stripsPosition (/Users/Max/projects/wfb/i18n-sync-tool/node_modules/eslint/lib/rules/no-duplicate-case.js:27:36)
    at stripsPosition (/Users/Max/projects/wfb/i18n-sync-tool/node_modules/eslint/lib/rules/no-duplicate-case.js:27:36)
    at stripsPosition (/Users/Max/projects/wfb/i18n-sync-tool/node_modules/eslint/lib/rules/no-duplicate-case.js:27:36)
    at stripsPosition (/Users/Max/projects/wfb/i18n-sync-tool/node_modules/eslint/lib/rules/no-duplicate-case.js:27:36)
 @ ./src/reducers/index.js 9:15-36
```

What am I doing wrong? Thanx

**Comment by lcjnil** [comment]
@godcore thanks for your response, It's a error caused by eslint, maybe it's bug. 
Please try out new master branch.

**Comment by lcjnil** [comment]
close via 1c69929

**Comment by lcjnil** [comment]
eslint/eslint#3440

**Comment by MaxNamazov** [comment]
Yeah, it works now. Thanx for quick response
